### ISSUE TITLE
Add a hint which version the documentation refers to 

### ISSUE THREAD

**Issue by krichter722** [networkx/website#1]
It is quite confusing to deal with the large variety of documentations for different version without a hint to which version the documentation belongs to (see attached screenshot). For starters it should be sufficient to reorganize the resources in the archive so that the version is reflected in the URL. Sooner or later the template for document generation could be adjusted to include a version in the header or sidebar.
![Uploading screenshot__missing_version_networkx_documentation.png . . .]()

It is also not useful to keep the URL ''.../latest/path/to/doc'' and not redirect is to ''.../version/path/to/doc'', it makes only sense to make the resource available under this URL before redirection. Keeping it will make people reference the "latest" URL which is not very useful if one relies to posts in other forums/Q&As which apply to a specific version and might still be useful after some time/versions.

**Comment by hagberg** [comment]
We can certainly change this easily.  Could you be more specific on what makes it easiest to understand?
(Your screenshot didn't work)

Right now we have
- http://networkx.github.io/documentation/development/ (built every night from github sources)
- http://networkx.github.io/documentation/latest/ (the latest released version)
- http://networkx.github.io/documentation/networkx-1.8
- http://networkx.github.io/documentation/networkx-1.7

and this link goes to all older versions back to networkx-0.36 (2008): http://networkx.lanl.gov/archive/
I'm pretty sure these is just historical information at this point, but I have been careful to archive it.

**Comment by hagberg** [comment]
I reorganized the links.  Does it make better sense now?

**Comment by krichter722** [comment]
Sorry, I can't recognize from your comment what you changed. I see now the ''Release: x.x'' row at the documentation root (but I don't remember if it has been already there). The issue persists. My idea was to redirect http://networkx.github.io/documentation/latest/genindex.html to http://networkx.github.io/documentation/1.8.1/genindex.html

I realized that this is a more widespread issue among projects (which I don't understand). I guess the king_queen of the hill is MySQL (providing links in the sidebar to review changes between versions) (which has not been part of my initial request), but I don't know if you want to reprogram your template engine that way.

BTW, in the footer I still see `© Copyright 2013, NetworkX Developers. Last updated on Aug 03, 2013. Created using Sphinx 1.2b1.`. Shouldn't that change after your update?

**Comment by hagberg** [comment]
You are right, my fixes don't add a version number to the text in the docs or redirect from latest->networkx-1.9 at all levels in the docs.  I don't control the webserver to do redirects.
But we could consider putting a version number somewhere in the doc text (other than the URL).  What is the current best practices for this?

**Comment by hagberg** [comment]
We are moving over to readthedocs http://networkx.readthedocs.org/ which will fix this issue.
