### ISSUE TITLE
source looks overwritten

### ISSUE THREAD

**Issue by jarrodmillman** [networkx/website#12]
@hagberg It looks like a890e0fdc25ac overwrote the source directory with the generated website, which should go here:
https://github.com/networkx/networkx.github.com

I originally left the ``Makefile`` as it was, since I didn't want to change too much.  However, the system is a bit old and I could replace it with ``ghp-import``:  https://github.com/davisp/ghp-import
I use it a lot and it works well.  This would allow me to delete ``_scripts`` and simplify the ``Makefile``.  It should also make it easier to avoid pushing the generated content to the source repo.

If that sounds reasonable, would you ``reset`` your ``master`` branch to 1235f2d8ded and then force push to ``networkx-website``.

(If it is more convenient for you, you could give me push access to ``networkx-website`` and I can fix this for.  If you want, you could also give me push access to ``networkx.github.com`` and I can update the actual website as well.)

**Comment by hagberg** [comment]
Oh yes,  I see I did a great job on that. 
@jarrodmillman I added you do the networkx dev team so you can fix my push here (and other nonsensical stuff I'll do in the future).

**Comment by jarrodmillman** [comment]
@hagberg I fixed and updated the source repo `networkx-website`.  I didn't have access to update the actual website repo `networkx.github.com`.  But it should be as simple as:

```
$ cd <where ever the networkx-website repo is>
$ git pull -f   # assuming you automatically pull from git@github.com:networkx/networkx-website.git
$ pip install -r requirements.txt  # or `pip install ghp-import` assuming you have the newest version of Sphinx
$ make github
```

**Comment by hagberg** [comment]
I added the networkx-dev team to 
https://github.com/networkx/networkx.github.com
so you can go ahead and push the website there.

**Comment by jarrodmillman** [comment]
Done.
