### ISSUE TITLE
Suggestion for the weighted_projected_graph documentation

### ISSUE THREAD

**Issue by JBPressac** [networkx/website#2]
Hello,
The [weighted_projected_graph documentation](http://networkx.github.io/documentation/networkx-1.9.1/reference/generated/networkx.algorithms.bipartite.projection.weighted_projected_graph.html#networkx.algorithms.bipartite.projection.weighted_projected_graph) could be clearer with the example of the Davis Southern Women graph and saying that (quoting [Jordi Torrens](https://groups.google.com/d/msg/networkx-discuss/WKKLevbUAgw/jqTS1ywP6CUJ)) the weight attribute of the weighted projected graph represents the number of shared neighbors in the bipartite network (ie the number of events that both women attended together). In fact, the term "shared neighbors" without example could lead to the confusion of a neighborhood between the nodes of the projected graph (the women or the events in the Davis Southern Women case).

**Comment by hagberg** [comment]
This request should be made over at the source code repository.
I made a PR there networkx/networkx#1332 that updates the Davis Club example.

**Comment by hagberg** [comment]
This request should be made over at the source code repository.
I made a PR there networkx/networkx#1332 that updates the Davis Club example.
