### ISSUE TITLE
Create more modern web front page

### ISSUE THREAD

**Issue by hagberg** [networkx/website#9]
We could use a more modern and stylish web front page.  
Docs and examples are elsewhere so it just needs to explain the basics of who/what/why etc. and look good.  Any volunteers?

**Comment by SanketDG** [comment]
Hi, I was trying the different inbuilt themes in Sphinx, and looks like `alabaster` makes the front page quite pretty.

![kazam_screenshot_00017](https://cloud.githubusercontent.com/assets/8980971/12053398/b2f65cc0-af3e-11e5-8f48-2a4ffacd3bc2.png)

Also, with `sphinx_rtd_theme`:

![kazam_screenshot_00018](https://cloud.githubusercontent.com/assets/8980971/12053431/0c03a1b0-af3f-11e5-9071-11386c4b626f.png)

Can we use any of the above, or is the intention a new custom theme?

**Comment by CrazyPython** [comment]
The Sphinx RTD theme is pretty ugly IMHO, esp. for a webfront site. It's okay for docs, though.

**Comment by jarrodmillman** [comment]
+1 on using alabaster.  Given how close we are to 2.0 (hopefully), why don't I just do a minimal update using the default theme and some misc. clean-ups?  I am not really much of a website designer, so I will make minimal changes.  But I think that should be sufficient unless someone else is interested in putting in more effort. @hagberg

**Comment by jarrodmillman** [comment]
I can coordinate any changes I make with my PR finalizing the changes to
  http://networkx.readthedocs.io/en/latest/

**Comment by hagberg** [comment]
Good idea.  I didn't know about alabster.
I don't think we need very much content there, just enough to advertise and get people quickly off to what they really want, so clean up accordingly.
